// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY-PQwZiGHS8UzP2SY6nM3MzxhPVZnkoY',
    appId: '1:896167967018:web:05f7288c37b71357a70653',
    messagingSenderId: '896167967018',
    projectId: 'xlam-app',
    authDomain: 'xlam-app.firebaseapp.com',
    storageBucket: 'xlam-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACJ59eKQaJbTVUQPoIiVN0oGdvw4DnpEk',
    appId: '1:896167967018:android:eebd73d6be264db7a70653',
    messagingSenderId: '896167967018',
    projectId: 'xlam-app',
    storageBucket: 'xlam-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgw2VYeaA8UwJ9MX2iP5ecLQLiTdZhyjU',
    appId: '1:896167967018:ios:0757b85380b49e7ca70653',
    messagingSenderId: '896167967018',
    projectId: 'xlam-app',
    storageBucket: 'xlam-app.appspot.com',
    iosBundleId: 'com.example.xlamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgw2VYeaA8UwJ9MX2iP5ecLQLiTdZhyjU',
    appId: '1:896167967018:ios:0757b85380b49e7ca70653',
    messagingSenderId: '896167967018',
    projectId: 'xlam-app',
    storageBucket: 'xlam-app.appspot.com',
    iosBundleId: 'com.example.xlamApp',
  );
}
